### ISSUE TITLE
Is this repo in sync with the source on sourcefourge?

### ISSUE THREAD

**Issue by ibakayoko** [colosa/processmaker#2551]
Hello,

Wondering if the git repo is in sync with the code on http://sourceforge.net/projects/processmaker/files/ProcessMaker/

Best Regards,
-Ibrahim

**Comment by tomolimo** [comment]
Hello,
I could say: more or less for 2.5.2, 2.8, and for the rest I'll check
regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello
Seems to be aligned with 3.0.1.5
regards,
Tomolimo

**Comment by tdondich** [comment]
Yes.  This is aligned and I understand how having multiple repository/locations can be confused.  We will work on simplifying this in the future.
