### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by jfastnacht** [colosa/processmaker#2557]
While the readme says "PHP 5.1.6 or greater" it's not running out of the box on PHP 7.

Is there anything planned for the near future?

**Comment by tdondich** [comment]
@jfastnacht We are tackling as we speak and intend to add PHP 7 support very soon.  We will be closing out this ticket; however, I understand it's not resolved.  We are actively working on it and you will see the support in the next couple of versions.
